[project]
name = "system-config"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
managed = true
dev-dependencies = [
    "ruff>=0.9",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["."]


# Exclude a variety of commonly ignored directories.
exclude = []

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"  # 您可以根据需要选择 'function', 'class', 'module', 'package', 'session'
