[manager]
ratio=[1,3,4]

[preview]
wrap="yes"

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = "nvim %0",   block = true, for = "windows" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
	{ run = '"C:\Program Files\mpv.exe" %*', orphan = true, for = "windows" }
]
open = [

	{ run = 'nvim "$@"', block = true, for = "unix" ,desc = "open"},
	{ run = "nvim %0",   block = true, for = "windows",desc = "open" },
]
